### ISSUE TITLE
Database Rollback

### ISSUE THREAD

**Issue by hizliemre** [koenbeuk/EntityFrameworkCore.Triggered#102]
how can i rollback automaticly all changes when trigger is failed? Can i use transaction?

**Comment by koenbeuk** [comment]
So to make sure I understand you correctly, You want to:
1) Modify your database and save that
2) Publish an event to an external service after you've modified your database
3) Ensure that you can rollback the database modifications in case the publishing failed

If that's the case then I would suggest using transactions. Simply wrap your dbContext.SaveChanges() in a try/catch block and start a transaction prior to calling dbContext.SaveChanges() and do a rollback when you catch an exception. if your IAfterSaveChanges trigger fails then it will throw an exception and cause the transaction to be rolled back. If it succeeds then it will cause the transaction to commit.

**Comment by hizliemre** [comment]
Yes right, that was my question. nice job.  i got my answer. this issue can be closed. 😊

**Comment by hizliemre** [comment]
@koenbeuk
Last question. If I use context.SaveChanges() more than once in my code block, what time the after save triggers are run? transaction.Commit() ?

**Comment by koenbeuk** [comment]
A call to SaveChanges really means the combo: `RaiseBeforeSaveChangeTriggers(); SaveToDatabaser(); RaiseAfterSaveChangeTriggers()`

Any call to SaveChanges within a trigger will then NOT raise triggers for Entity/ChangeType combinations for which triggers have already been raised
