### ISSUE TITLE
Abstract classes are trying to be instantiated with dependency injection

### ISSUE THREAD

**Issue by Unskilledcrab** [koenbeuk/EntityFrameworkCore.Triggered#111]
I am trying to implement an abstract class seen below

`

        public abstract class BaseAfterSaveTrigger<TEntity> : IAfterSaveTrigger<TEntity>
        where TEntity : class
    {

        private readonly OriginalTechSystemsContext dbcontext;

        public BaseAfterSaveTrigger(OriginalTechSystemsContext dbcontext)
        {
            this.dbcontext = dbcontext;
        }

        public async Task AfterSave(ITriggerContext<TEntity> context, CancellationToken cancellationToken)
        {
            var entity = context.Entity;

            var task = context.ChangeType switch
            {
                ChangeType.Added => OnAdded(entity),
                ChangeType.Modified => OnAdded(entity),
                ChangeType.Deleted => OnAdded(entity),
                _ => throw new System.NotImplementedException(),
            };

            await task;
            await dbcontext.SaveChangesAsync(cancellationToken);
        }

        public virtual Task OnAdded(TEntity addedEntity) => Task.CompletedTask;

        public virtual Task OnModified(TEntity modifiedEntity) => Task.CompletedTask;

        public virtual Task OnDeleted(TEntity deletedEntity) => Task.CompletedTask;
    }
`

I am getting the following error 
![image](https://user-images.githubusercontent.com/12536115/126249187-707c7727-cc06-462f-92c4-81cf7db57266.png)

I believe the DI system is not ignoring abstract classes

**Comment by koenbeuk** [comment]
Thanks for reporting this, 

I assumed that you are calling AddAssemblyTriggers in order for the app to auto discover your triggers. If not, let me know.

A fix for this issue is present in master and will be released within the next couple of days

**Comment by Unskilledcrab** [comment]
Yes sorry, I am using the AddAssemblyTriggers for auto discovery. Thank you for the quick response!

**Comment by Unskilledcrab** [comment]
I watched the ef core community stand up and found your library through that. I really love the abstraction it makes 😍 thank you for building it!

I had a question regarding a feature I think would be useful, would you like me to submit another issue to discuss?

**Comment by koenbeuk** [comment]
@Unskilledcrab I'm happy to hear that this library is working for you :)

Feel free to open up a new issue or start a new discussion over here: https://github.com/koenbeuk/EntityFrameworkCore.Triggered/discussions
