### ISSUE TITLE
Trigger BeforeSave executes, however new data is not saved in database fields.

### ISSUE THREAD

**Issue by victorperez2911** [koenbeuk/EntityFrameworkCore.Triggered#118]
hi

Following Getting Started, everything appears to be correct in my implementation, including the fact that triggers are executed.

However, new data is not saved in the database.

Details

Trigger

```csharp
public class EmpresasSetChangedAtTrigger : IBeforeSaveTrigger<Empresa>
    {

        public Task BeforeSave(ITriggerContext<Empresa> context, CancellationToken cancellationToken)
        {

            if (context.ChangeType == ChangeType.Modified)
            {
                context.Entity.ChangedAt = DateTimeOffset.Now;
            }

            return Task.CompletedTask;
        }

    }
```

Register DbContext in Startup
```csharp
services.AddDbContext<TenantDbContext>((serviceProvider, optionsBuilder) =>
            {
                var CurrentTenant = serviceProvider.GetRequiredService<ICurrentTenant>();

                var TenantConnString = MultiTenantUtils.TenantConnStringFactory(CurrentTenant, _configuration);

                optionsBuilder.UseSqlServer(TenantConnString);

                optionsBuilder.UseTriggers(triggerOptions =>
                {
                    var TriggerAssembly = CurrentAssemblyUtils.GetCurrent();
                    triggerOptions.AddAssemblyTriggers(TriggerAssembly);
                });

            })
            //.AddScoped<IBeforeSaveTrigger<Nfe>, NfeSetChangedAtTrigger>()
            //.AddTransient<IBeforeSaveTrigger<Empresa>, EmpresasSetChangedAtTrigger>()
            ;
```

Any Tips ?

**Comment by koenbeuk** [comment]
Hi @victorperez2911 

So I assume that you're referring to the ChangedAt property, not getting persisted in the database? 

I don't see a particular issue with your code. It may be that you have your mapping is incorrectly configured or that you have another trigger that Unsets the ChangedAt property.

Can you share the log output of when saving an Entity?

In appsettings.json:
```json
"Logging": {
    "LogLevel": {
      "EntityFrameworkCore.Triggered.TriggerSession": "Information",
      "Microsoft.EntityFrameworkCore": "Information"
    }
  }
```

And in your startup class:

```csharp
services.AddDbContext(optionsBuilder => {
    optionsBuilder.UseSqlServer(...);
    optionsBuilder.EnableSensitiveDataLogging(true);
})
```

This should show you that the trigger runs and that the Update statement includes the new timestamp.

Thanks

**Comment by victorperez2911** [comment]
Hi

More details

1) I have only one Trigger.

2) And a found the root cause of the issue, the particular property is from a model base classe inheritance.

3) Implementing the Trigger from the model base class also does not work.

**Comment by koenbeuk** [comment]
I'm using properties from base models currently with no issues. Can you share your logs as suggested before or ideally, share a repro of this issue? Thanks!

**Comment by victorperez2911** [comment]
Problem solved.

We used INotifyPropertyChanged and INotifyPropertyChanged as change detection strategy in the Entity Framework and the base class did not implement the correct interface, and also did not raise the correct event in this property (ChangedAt) .

Thanks.
