### ISSUE TITLE
Notwork with DbContextFactory<DbContext>

### ISSUE THREAD

**Issue by iamkisly** [koenbeuk/EntityFrameworkCore.Triggered#119]
Do not work with `DbContextFactory<DbContext>`. 
With a certain version of the framework, the "AddDbContextFactory" method has become available, which makes it possible to pass a factory to the constructor. 
```
            services.AddDbContextFactory<DataContext>(optionsBuilder =>
            {
                optionsBuilder.UseNpgsql(Configuration.GetConnectionString("DefaultConnection"));
                optionsBuilder.UseTriggers();
            });
```
If we transfer a factory, or a pool of factories, then your triggered solution does not work.

**Comment by koenbeuk** [comment]
Hi @iamkisly 

This is covered in the readme: https://github.com/koenbeuk/EntityFrameworkCore.Triggered#dbcontext-pooling

In short, change  
```csharp
services.AddDbContextFactory<DataContext>(optionsBuilder => ...);
```
to 
```csharp
services.AddTriggeredDbContextFactory<DataContext>(optionsBuilder => ...);
```

Let me know if this is working for you. Thanks
