### ISSUE TITLE
Support for .NET 6

### ISSUE THREAD

**Issue by DavidErben** [koenbeuk/EntityFrameworkCore.Triggered#120]
Hi Koen,

hope you are doing well! I just tried out to upgrade to .NET 6 RC1 and noticed that unfortunately some exceptions are thrown. Do you plan to support .NET 6 soon or will you wait for the GA release?

Error:

	An error occurred while starting the application.
	TypeLoadException: Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EntityFrameworkCore.Triggered, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e4acff2b88bee728' does not have an implementation.

	EntityFrameworkCore.Triggered.Infrastructure.Internal.TriggersOptionExtension.get_Info() in TriggersOptionExtension.cs, line 55

		TypeLoadException: Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'EntityFrameworkCore.Triggered, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e4acff2b88bee728' does not have an implementation.
			EntityFrameworkCore.Triggered.Infrastructure.Internal.TriggersOptionExtension.get_Info() in TriggersOptionExtension.cs

			public DbContextOptionsExtensionInfo Info => (DbContextOptionsExtensionInfo) this._info ?? (DbContextOptionsExtensionInfo) (this._info = new TriggersOptionExtension.ExtensionInfo((IDbContextOptionsExtension) this));

	Microsoft.EntityFrameworkCore.DbContextOptions.GetHashCode()
	System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd<TArg>(TKey key, Func<TKey, TArg, TValue> valueFactory, TArg factoryArgument)
	Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, bool providerRequired)
	Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
	Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityUserContext<TUser, TKey, TUserClaim, TUserLogin, TUserToken>..ctor(DbContextOptions options)
	Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext<TUser, TRole, TKey, TUserClaim, TUserRole, TUserLogin, TRoleClaim, TUserToken>..ctor(DbContextOptions options)
	Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext<TUser, TRole, TKey>..ctor(DbContextOptions options)
	LC.Box.Service.OrderManagement.Infrastructure.Contexts.AuditableDbContext..ctor(DbContextOptions options, IClientConfiguration clientConfiguration, ICurrentUserService currentUserService, ILogger<LabCubeOrderDbContext> logger) in AuditableDbContext.cs

Thanks in advance! :)

**Comment by DavidErben** [comment]
Great, thank you!

**Comment by koenbeuk** [comment]
I'm planning on releasing a new beta version within the next 24 hours that includes support for EF Core 6.
