### ISSUE TITLE
Could not load file or assembly 'EntityFrameworkCore.Triggered.Abstractions'

### ISSUE THREAD

**Issue by jasemy** [koenbeuk/EntityFrameworkCore.Triggered#122]
Hello Mr. Koen.

Thank you for your excellent contributions in GitHub. I have installed EntityFrameworkCore.Triggered version 1.4.0. Everything works perfectly in Windows applications. When I tried to use it in an ASP.NET Website project I got the following error (note Abstractions):

_Could not load file or assembly 'EntityFrameworkCore.Triggered.Abstractions' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)_

I have tried almost every possible workaround I found in google but nothing works.

I can't update to newer .NET versions (3.1+) due to client financial restrictions.

Would you kindly give me a hint at any possible workaround? Thank you in advance.

- Jasem

**Comment by koenbeuk** [comment]
Hi @jasemy 

I'll have to see If I can reproduce this issue this weekend, in the meantime:

Have you tried building the project locally without strong name signing? What you can do:
1. clone https://github.com/koenbeuk/EntityFrameworkCore.Triggered/tree/v1.4.0
2. edit src/Directory.Build.props and remove the line saying: `<SignAssembly>true</SignAssembly>`
3. run a normal build or pack

This should at least give you unsigned assemblies that you can then use locally. Let me know how it goes!

**Comment by jasemy** [comment]
Hello Koen.

> Let me know how it goes!

Everything is perfect now! I followed your steps and the web application is working nicely now. No issues at all.

Thank you and I wish you the best of luck.

Jasem
