### ISSUE TITLE
Risk using async trigger behind a sync SaveChanges() call?

### ISSUE THREAD

**Issue by benmccallum** [koenbeuk/EntityFrameworkCore.Triggered#127]
Hey! We've still got plenty of sync `SaveChanges()` calls in our codebase that we're slowly getting rid of but it did make me wonder whether there's a risk to writing an async trigger behind a sync call.

Before we dive in fully we might need to eliminate all our legacy sync SaveChanges() calls.

**Comment by benmccallum** [comment]
cc: @anthonykeller

**Comment by benmccallum** [comment]
Thanks @koenbeuk , good to know. I think I might make a concerted effort to async all our things to be sure. 

It might be worth linking this issue from a disclaimer on the readme/docs if you think it warrants it.

**Comment by koenbeuk** [comment]
@benmccallum I'm open for that. Would you mind issuing a PR?
