### ISSUE TITLE
AddTrigger() and AddAssemblyTriggers() don't fully register a trigger type if another is already registered for the same interface implementation

### ISSUE THREAD

**Issue by RNTenant** [koenbeuk/EntityFrameworkCore.Triggered#140]
Good day. I've come to report an issue with the library's trigger type registration APIs.

For the context of this issue, let the following be considered:
- `DbCtx` - a `DbContext` type;
- `Entity` - an entity type, whose persistance of entities is managed through a configured `DbCtx` instance;
- `EntityBeforeTrigger` - a registered trigger type that implements `IBeforeSaveTrigger<Entity>`;
- `EntityAfterTrigger1` - a registered trigger type that implements `IAfterSaveTrigger<Entity>`;
- `EntityAfterTrigger2` - another registered trigger type that implements `IAfterSaveTrigger<Entity>`;
- all of the aforementioned types, except `Entity`, are defined in the same assembly.

The library makes it possible to register the 3 listed trigger types as services, through calls to the `AddTrigger()` and `AddAssemblyTriggers()` extension methods. However, doing so would prevent the `EntityAfterTrigger2` type's `AfterSave()` method from ever being called by the library, assuming `EntityAfterTrigger2` is registered after `EntityAfterTrigger1`.
All overloads of the `AddTrigger()` and `AddAssemblyTriggers()` methods are affected by this problem.

The above happens because the library's trigger type registration APIs only register at most one type for each possible interface implementation, using calls to `services.TryAdd()`. This prevents multiple trigger types that match the same interface implementation from being discovered by the `TriggerSession.RaiseTriggers()` method, which itself handles their dispatchment.
The following code snippet would allow the library to properly discover all 3 of the aforementioned trigger types:
```csharp
services.AddScoped<IBeforeSaveTrigger<Entity>, EntityBeforeTrigger>();
services.AddScoped<IAfterSaveTrigger<Entity>, EntityAfterTrigger1>();
services.AddScoped<IAfterSaveTrigger<Entity>, EntityAfterTrigger2>();
```

The following code excerpts highlight the location of calls to `services.TryAdd()` within the trigger type registration APIs.

In the `ServiceCollectionExtensions.RegisterTriggerTypes()` static method:
https://github.com/koenbeuk/EntityFrameworkCore.Triggered/blob/634a441dcef8caf692e0b5fbd09e90cc01b254f8/src/EntityFrameworkCore.Triggered.Extensions/ServiceCollectionExtensions.cs#L35-L38
In the non-chaining `ServiceCollectionExtensions.AddAssemblyTriggers()` method overload:
https://github.com/koenbeuk/EntityFrameworkCore.Triggered/blob/634a441dcef8caf692e0b5fbd09e90cc01b254f8/src/EntityFrameworkCore.Triggered.Extensions/ServiceCollectionExtensions.cs#L90-L100

**Comment by koenbeuk** [comment]
Thanks for reporting this! It seems indeed to be the case that `services.AddAssemblyTriggers` and `services.AddTrigger` are failing to register multiple triggers of the same type.

This does not affect `triggerOptions.AddAssemblyTriggers` and `triggerOptions.AddTrigger` which are the recommended way of registering Triggers.

As a workaround, either manually register the triggers as shown by the author: `services.AddTransient<IBeforeSaveTrigger<Entity>, MyEntityTrigger1>()` or register them with the triggerContextOptionsBuilder, e.g.:

```csharp
services.AddDbContext<MyDbContext>(options => {
    options.UseTriggers(triggerOptions => {
      triggerOptions.AddTrigger<MyTrigger>();
      ...
    })
});
```

I'll see if I can get a fix in shortly
