### ISSUE TITLE
Getting a service scoped to a dbcontext from a trigger

### ISSUE THREAD

**Issue by benmccallum** [koenbeuk/EntityFrameworkCore.Triggered#143]
Hey!

I've got a use case where I'd like to generically track a bunch of changes to certain entities after a save, group them by a key, then fire notifications/emails off for those keys.

I gave this a go via the following setup:
* Scoped service `SupplierDataChangedContext` which has a list property that changes can be added to.
* An after save trigger `IAfterSaveTrigger<ISupplierData>` which injects `SupplierDataChangedContext` and adds to its list relevant changes.
* `IAfterSaveCompletedTrigger` called `SupplierDataChangedPublisher` which injects the `SupplierDataChangedContext` and does the aggregation of supplier data changes and sending of notifications

The problem I feel like I have though is that ideally `SupplierDataChangedContext` would be scoped to the DbContext the trigger has. 

So I guess I'm wondering:
  1. If I inject my DbContext into a trigger, is that guaranteed to be the same one that the trigger fired from?
  2. How can I get a hold of a service who's lifetime is the same as the DbContext, or in the case of pooling, the rented lifetime?

Thanks, Ben

**Comment by koenbeuk** [comment]
Hi Ben,

Regarding your questions:

>1. If I inject my DbContext into a trigger, is that guaranteed to be the same one that the trigger fired from?

This is guaranteed for as long as you register your DbContext in the following ways:
- `AddDbContext` for a normal registration
- `AddTriggeredDbContextPool` for a pooled db context
- `AddTriggeredDbContextFactory` for a factory registration

Support is provided (for pooled and factory registrations) by the use of a [hybrid service provider](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/blob/a402e840bebd671750dd7909c6d8bfc85c0a2729/src/EntityFrameworkCore.Triggered/Internal/HybridServiceProvider.cs#L20) which gets [configured](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/blob/a402e840bebd671750dd7909c6d8bfc85c0a2729/src/EntityFrameworkCore.Triggered/Internal/TriggeredDbContextFactory.cs#L57) when calling the `AddTriggeredDbContext...` counterparts.

> 2. How can I get a hold of a service who's lifetime is the same as the DbContext, or in the case of pooling, the rented lifetime?

Triggers are constructed through a [TriggerInstanceFactory](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/blob/a402e840bebd671750dd7909c6d8bfc85c0a2729/src/EntityFrameworkCore.Triggered/Internal/TriggerInstanceFactory.cs#L43) which uses the same HybridServiceProvider to satisfy its DI needs. In this case the Hybrid service provider encapsulates the DbContext instance as well as the ServiceProvider that was used to obtain the DbContext.

As for the type of trigger you're designing, I've implemented similar triggers as the following:
```csharp
triggerOptions.AddTrigger<SendUpdateEmail>(ServiceLifetime.Scoped);

class SendUpdateEmail : IAfterSaveTrigger<MyEntity>, IAfterSaveCompletedTrigger {
    readonly Dictionary<string, List<MyEntity>> _pendingEntities = new();
    readonly IEmailService _emailService;

    public SendUpdateEmail(IEmailService emailService) {
         _emailService = emailService;
    }
    
    public Task AfterSave(ITriggerContext<MyEntity> context, CancellationToken _) {
        if (!_pendingEntities.Contains(context.Entity.UserId)) {
            _pendingEntities[context.Entity.UserId] = new List<MyEntity>();
        }
        _pendingEntities[context.Entity.UserId].Add(context.Entity);
    }

    public async Task AfterSaveCompleted(CancellationToken _) {
        foreach (var entry in _pendingEntities) {
           await _emailService.SendToUser(entry.Key, entry.Value); // or whatever
        }
    }
}
```

```
```
