### ISSUE TITLE
How fire trigger after delete ICollection of Entities

### ISSUE THREAD

**Issue by MrSuperGeek** [koenbeuk/EntityFrameworkCore.Triggered#149]
Hello
Thank you for this wonderful extension, i have an issue whene i try to fire the trigger after deleteing IColletion of enyity.

**Comment by koenbeuk** [comment]
I'm not getting the question, can you clarify your issue? thanks.

**Comment by MrSuperGeek** [comment]
For example i have a trigger after deleting a Student and the latter is a child of the School, so when i try to delete School with a Collection of Students the trigger of Student not working.

**Comment by MrSuperGeek** [comment]
Thanks for your feedback.
I did not understand everything, except me I want that once a School will be deleted at the same time we delete the Students childs and for each Student we trigger a Trigger.
