### ISSUE TITLE
Scoped Dependency Issue

### ISSUE THREAD

**Issue by anthony-keller** [koenbeuk/EntityFrameworkCore.Triggered#156]
This issue may prove tricky to repro, so I'll explain the issue and you can advise on further action.

This image shows some logs containing the HttpContext TraceIdentifier, the DbContext Id and a Guid in a scoped dependency RequestAuthVariables.

![image](https://user-images.githubusercontent.com/31554139/184289087-6c0661fd-7d7d-42e3-b707-5261f3850a0b.png)

The highlighted rows show that two different HttpContexts get the same instance of RequestAuthVariables.

This is an intermittent issue in our production system and we've been able to reproduce in an integration test using a Parallel.ForEachAsync loop of 100. A loop of 10 typically works correctly and even the loop of 100 occasionally works.

Our interim solution is to register our triggers as Transient instead of Scoped.

We're using the `AddTriggeredDbContextPool` and `AddTriggeredPooledDbContextFactory`

@benmccallum and I are happy to try and work with you as needed.

**Comment by koenbeuk** [comment]
@anthony-keller Haven't had a chance to look into this yet, will have more time in the coming weeks. If you have a repro, that would be super useful! I tried to recreate this issue once without success.

**Comment by anthony-keller** [comment]
@koenbeuk I can repro in our codebase so perhaps at some point we could jump on a Zoom/Meet/Teams to debug

**Comment by koenbeuk** [comment]
@anthony-keller Happy to do so, please sent me a ping at koen@linker.io so that we can arrange a time and virtual place. Thanks!

**Comment by koenbeuk** [comment]
We found a memory leak issue in #168 that may have caused this issue. We should test if this is still an issue after updating to v3.2.2

**Comment by anthony-keller** [comment]
I did report a potential regression on the pr about 30 mins ago

**Comment by anthony-keller** [comment]
I'll test this issue as well

**Comment by anthony-keller** [comment]
I'm still table to reproduce this issue on 3.2.2.
