### ISSUE TITLE
[Performance] Sync. / ValueTask version of IBeforeSaveTrigger<T>

### ISSUE THREAD

**Issue by vertonghenb** [koenbeuk/EntityFrameworkCore.Triggered#164]
Given the Trigger below:
> Notice that we're not doing anything`async`, aren't we always setting up a Task state machine for nothing?
```cs
public class EntityBeforeSaveTrigger : IBeforeSaveTrigger<Entity>
{
    public Task BeforeSave(ITriggerContext<Entity> context, CancellationToken cancellationToken)
    {
        if (context.ChangeType == ChangeType.Added)
        {
            context.Entity.CreatedAt = DateTime.UtcNow;
            context.Entity.UpdatedAt = DateTime.UtcNow;
        }

        if (context.ChangeType == ChangeType.Modified)
        {
            context.Entity.UpdatedAt = DateTime.UtcNow;
        }
        return Task.CompletedTask; // Should not be needed.
    }
}
```

We can't implement the void overload although it's part of the package:
[IBeforeSaveTrigger<T>](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/blob/59c59832db35b71310ef7d6520e445804c49d182/src/EntityFrameworkCore.Triggered.Abstractions/IBeforeSaveTrigger.cs#L6)

> Notice that the compiler will complain about `Interface not implemented`
```cs
public class EntityBeforeSaveTrigger : IBeforeSaveTrigger<Entity>
{
    public void BeforeSave(ITriggerContext<Entity> context)
    {
        if (context.ChangeType == ChangeType.Added)
        {
            context.Entity.CreatedAt = DateTime.UtcNow;
            context.Entity.UpdatedAt = DateTime.UtcNow;
        }

        if (context.ChangeType == ChangeType.Modified)
        {
            context.Entity.UpdatedAt = DateTime.UtcNow;
        }
    }
}
```

Why is this and can't we create a ValueTask overload?

Version: 3.2.1

PS: Package is awesome.

**Comment by koenbeuk** [comment]
Sharp eye! v3.2.1 only offers asynchronous triggers. The IBeforeSaveTrigger that you shared is part of development for v4 that offers both synchronous and asynchronous triggers, this is introduced with [this PR](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/pull/161).

I'm planning on releasing v4 preview.1 in the coming days, I just need to update the README. Haven't gotten around to do so yet.

**Comment by vertonghenb** [comment]
@koenbeuk Awesome! If you need help with anything let me know.
