### ISSUE TITLE
Transaction Exception on Save Changes

### ISSUE THREAD

**Issue by arex388** [koenbeuk/EntityFrameworkCore.Triggered#173]
Hello. I recently published a large update to a project I manage. One of the things that was added with the update was to shift away from database-side triggers to application-side triggers with EFC.T. It seemed to work well during beta testing, but in production there are random exceptions being thrown which are causing headaches. Refreshing right after the exception works as expected.

> InvalidOperationException: The specified transaction is not associated with the current connection. Only transactions associated with the current connection may be used.

I initially assumed it was with some triggers that have the DbContext injected into them, thinking it was a new instance being injected. I've since removed those triggers. It didn't help. I then removed the simpler triggers that change simple properties, such as modified at and by. Also didn't work. I have one trigger left that's a little more complex, but it looks like I'll have to remove it and disable EFC.T from my project.

I'm sad to do that, but I need to have stability in the live system, and the triggers and or triggered context is interfering with that. Would you be able to look into this for a future update? I'd much prefer to use the triggers, especially application-side since database-side is difficult to manage.

My project is on ASP.NET Core 6 with EntityFramework Core 6 running on Windows Server 2019 1809 (I believe) IIS. Will be updating to 7 soon-ish, if that matters to you.

Thanks!

**Comment by koenbeuk** [comment]
> I initially assumed it was with some triggers that have the DbContext injected into them
I use this pattern on multiple projects that are all running in production without issues. Note that you will need to make sure that the DbContext is registered as a Scoped (default) or singleton in order to be able to receive the correct DbContext. Alternatively, you can install `EntityFrameworkCore.Triggered.Extensions` which offers an extension method to get the dbContext straight from the ITriggerContext.

> Would you be able to look into this for a future update

Without more context or a repro, there is not much I can do. However if you can provide more context or the repro, I'll be happy to take a look.

**Comment by arex388** [comment]
Well, the funny thing is, I disabled the triggers that were getting the DbContext injected last week and it still kept doing it. I've since disabled the last remaining trigger that just did property changes based on old vs new entity.

Before I disabled this last trigger just hitting save on a page would cause the exception at random within the first 2-4 attempts. After it was disabled, no exceptions with 10 saves in a row.

Could it be something to do with the `AddTriggeredDbContextPool` extensions? Maybe I'm misconfiguring something or misusing the triggers? Here's how I'm configuring the DbContext and how I write the triggers, can you spot an issue?:

```c#
public static IServiceCollection AddApplicationDbContextPool(
	this IServiceCollection services,
	IConfig config,
	int poolSize = 1024) {
	if (config is null) {
		throw new ArgumentNullException(nameof(config));
	}

	services.AddTriggeredDbContextPool<XyzContext>(
		_ => {
			_.UseSqlServer(config.DefaultConnection,
						   __ => {
							   __.UseNetTopologySuite();

							   if (!config.IsDevelopment) {
								   return;
							   }

							   __.CommandTimeout(int.MaxValue);
						   });
			.UseTriggers(
			 __ => __.AddAssemblyTriggers());

			if (!config.IsDevelopment) {
				return;
			}

			_.EnableDetailedErrors()
			 .EnableSensitiveDataLogging();
		}, poolSize);

	services.AddDbContextPool<SerilogContext>(
		_ => {
			_.UseSqlServer(config.SerilogConnection,
						   __ => {
							   __.UseNetTopologySuite();

							   if (!config.IsDevelopment) {
								   return;
							   }

							   __.CommandTimeout(int.MaxValue);
						   });

			if (!config.IsDevelopment) {
				return;
			}

			_.EnableDetailedErrors()
			 .EnableSensitiveDataLogging();
		});

	NtsGeometryServices.Instance = new NtsGeometryServices(
		NetTopologySuite.Geometries.Implementation.CoordinateArraySequenceFactory.Instance,
		new PrecisionModel(1000d),
		4326,
		GeometryOverlay.NG,
		new CoordinateEqualityComparer()
	);

	return services;
}
```

```c#
public sealed class ModifiableEntityBeforeSaveTrigger :
	IBeforeSaveTrigger<IModifiableEntity> {
	private readonly IIdentityProvider _identity;

	public ModifiableEntityBeforeSaveTrigger(
		IIdentityProvider identity) => _identity = identity;

	public Task BeforeSave(
		ITriggerContext<IModifiableEntity> context,
		CancellationToken cancellationToken) {
		OnAddedOrModified(context);

		return Task.CompletedTask;
	}

	private void OnAddedOrModified(
		ITriggerContext<IModifiableEntity> context) {
		if (context.ChangeType == ChangeType.Deleted
			|| !_identity.UserId.HasValue) {
			return;
		}

		var entity = context.Entity;

		entity.ModifiedAtUtc = DateTimeOffset.UtcNow;
		entity.ModifiedById = entity.ModifiedById == User.SystemId
			? User.SystemId
			: _identity.UserId.Value;
	}
}
```

Not sure if it matters, but I keep the DbContext and models in one assembly, and have an extension assembly that has the triggers, and other extensions as well as the `IServiceCollection` extensions in it. The applications, 7 of them, then use this shared extensions assembly to build up their services.

**Comment by koenbeuk** [comment]
Some additional questions:

What version of this library are you using? Also, you're only able to reproduce this in production? What is the difference between your dev environment and production environment?

**Comment by arex388** [comment]
- I am using 3.2.2 for EFC.T and EFC.T.Extensions.
- I am able to reproduce this in dev and production.
- The only difference between environments is the injected config parameters, such as database connection strings, coming AWS SSM Parameter Store. That and dev and staging have very low traffic, basically idle, while production has higher traffic.
