### ISSUE TITLE
Trigger not firing when using ExecuteDeleteAsync in EF Core 7.0

### ISSUE THREAD

**Issue by MhammdAli** [koenbeuk/EntityFrameworkCore.Triggered#175]
Hi all,

I'm having an issue with the new feature in EF Core 7.0 when using ExecuteDeleteAsync and ExecuteUpdateAsync. Specifically, the trigger is not firing because the ExecuteDeleteAsync method works as one SQL command.

Has anyone else encountered this issue, and if so, how did you solve it? Any insights or suggestions would be greatly appreciated.

Thanks in advance.

**Comment by koenbeuk** [comment]
I have not had a chance to use the new EF bulk update and delete features but from my understanding, this is not affecting EF's ChangeTracker but rather it gets applied directly on the database. 

This project relies on EF's ChangeTracker to work. Triggers should therefore not be compatible with EF Cores bulk update features.

**Comment by MhammdAli** [comment]
I'm considering using CreateTriggerSession() in dbContext extension method to raise additional events. Is it safe to use this method in terms of performance and reliability?

**Comment by koenbeuk** [comment]
Yes, that method is exposed in case you want to fire additional trigger types or take control in when triggers should be fired. [Transaction Triggers](https://github.com/koenbeuk/EntityFrameworkCore.Triggered#transactions) are an example of this.
