### ISSUE TITLE
Subtle issues when validating entities

### ISSUE THREAD

**Issue by kjkrum** [koenbeuk/EntityFrameworkCore.Triggered#179]
I've been thinking about the subtleties of validating entities that depend on values in relations. For example, a parent entity representing a group of `Foo` might have a `FooType` property, and its child entities must all have the same `FooType`. The triggers for both the parent and child entities would examine related entities to validate a new or changed entity's `FooType`.

But we also have to consider that related entities may have uncommitted changes. The problem can be minimized by keeping units of work small. Still, it's impossible to anticipate what combinations of changes may be saved together.

So the principle I've come up with is that a trigger should always assume that unsaved changes to other entities are valid, and base the validation of its own entity on the modified values of the other entities. If this assumption is incorrect, the triggers responsible for the other entities should abort the transaction.

Triggers may also need to account for the intricacies of `DetectChanges`.

Are there any other concerns along these lines that I should be aware of? I didn't see anything in the wiki about this kind of thing.

**Comment by koenbeuk** [comment]
Hey @kjkrum

Perhaps I'm not completely comprehending your question and perhaps you can clarify. A few things:

> a trigger should always assume that unsaved changes to other entities are valid

In my experience, triggers should strictly follow the single responsibility pattern, This means that a trigger either validates a particular condition, e.g. `ChildEntity.FooType == ChildEntity.Owner.FooType` or a trigger enforces a particular condition: `ChildEntity.FooType = ChildEntity.Owner.FooType`. In either case, I'm not sure why an assumption like that would matter. A different trigger might enforce that `Owner.FooType != FooType.Disallowed` in which case the whole set still fails.

> Triggers may also need to account for the intricacies of DetectChanges.

Can you share an example where triggers have to worry about the intricacies of DetectChanges? In my experiences, triggers only need to worry about their implementation as well as other 'related' triggers.

>  I didn't see anything in the wiki about this kind of thing.

Yeah, the docs are currently bare minimum. All the help to make this better would be greatly appreciated

**Comment by kjkrum** [comment]
Thanks for your response. To use my example of related entities that have property values that must be validated against each other in some other way, the trigger for one entity should usually compare its own *current* values to the other entity's *current* values, not either entity's `OriginalValues`.

My main concern about `DetectChanges` was the timing of when it's called. Looking at the code, I think it's called before any trigger is invoked (in hindsight, how else would it know what triggers to invoke?) and again before each cascading/recursive pass. So references should already be fixed up before triggers see them. I think that should be mentioned in the docs.

There are still some gotchas if a trigger needs to examine related entities. For example, deleted entities aren't removed from collection navigations until `SaveChanges` actually runs ([efcore #29486](https://github.com/dotnet/efcore/issues/29486)). I think this is different in EF Core vs. EF 6 and has confused some people. (Myself included.) And Arthur Vickers said it might be revisited again, so it's something to keep an eye on.

**Comment by koenbeuk** [comment]
> So references should already be fixed up before triggers see them. 

Exactly!

> I think that should be mentioned in the docs.

The docs need a general refresh and it would be great if we can can explicitly explain how ChangeTracking is used and when triggers exactly are executed within the pipeline. Thanks for brining that up. We'll keep this issue open until we've updated the docs. As always, PR's are most welcome

**Comment by kjkrum** [comment]
Another little gotcha that isn't unique to this library but is likely to come up when using it: an entity added to a `DbSet` is not included in an enumeration of that `DbSet` until changes are saved. This seems asymmetric with the way EF resolves tracked modified entries.
