### ISSUE TITLE
Ilogger in IAfterSaveTrigger<T> class causes DI error 

### ISSUE THREAD

**Issue by Piggy69** [koenbeuk/EntityFrameworkCore.Triggered#180]
Following the wiki examples, I created my trigger class as

`    public class DeviceMessageTrigger : IAfterSaveTrigger<DeviceMessage>
    {
        protected readonly JAoTSQLContext _context;
        protected readonly ILogger _logger;

        public DeviceMessageTrigger(JAoTSQLContext context, ILogger<DeviceMessageTrigger> logger)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task AfterSave(ITriggerContext<Device_Message> context, CancellationToken cancellationToken)
        {
            switch (context.ChangeType)
            {
                case ChangeType.Added:
                    _logger.LogDebug("Executing Trigger Action");
                    await _context.ServiceBroker_DeviceMessageAdded(context.Entity.DeviceMessageID, context.Entity.DeviceID);
                    break;
------ continue
`

and registered the trigger in both the context itself

`  protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(_connectionString, x =>
                {
                    x.UseNetTopologySuite();
                    x.CommandTimeout(GetConnectionTimeout());
                });
                optionsBuilder.UseTriggers(o =>
                {
                    o.AddTrigger<DeviceMessageTrigger>();
                    o.AddTrigger<ConfigurationDownlinkPayloadTrigger>();
                });
            }
        }
`
and in the Progam.Main services configuration:

`
  services.AddDbContext<JAoTSQLContext >(options =>
        {
            options.UseSqlServer();
            options.UseTriggers(t =>
            {
                t.AddTrigger<DeviceMessageTrigger>();
                t.AddTrigger<ConfigurationDownlinkPayloadTrigger>();
            });
        });
`

Compilation and application startup are OK, but as soon as an insert into the table is run I get this error stating that the DI cannot create the logger instance.

ERROR|DataConnectors.SQLConnector.Log_DefaultError|Error raised while executing operation SaveDeviceMessageData.|System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger`1[DataConnectors.EFCore.EFTrigger.DeviceMessageTrigger]' while attempting to activate 'DataConnectors.EFCore.EFTrigger.DeviceMessageTrigger'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method878(Closure, IServiceProvider, Object[])
   at EntityFrameworkCore.Triggered.Internal.TriggerInstanceFactory`1.Create(IServiceProvider serviceProvider)
   at EntityFrameworkCore.Triggered.Internal.TriggerFactory.Resolve(IServiceProvider serviceProvider, Type triggerType)+MoveNext()
   at EntityFrameworkCore.Triggered.Internal.TriggerDiscoveryService.DiscoverTriggers(Type openTriggerType, Type entityType, Func`2 triggerTypeDescriptorFactory)
   at EntityFrameworkCore.Triggered.TriggerSession.RaiseTriggers(Type openTriggerType, Exception exception, ITriggerContextDiscoveryStrategy triggerContextDiscoveryStrategy, Func`2 triggerTypeDescriptorFactory, CancellationToken cancellationToken)
   at EntityFrameworkCore.Triggered.Internal.TriggerSessionSaveChangesInterceptor.SavedChangesAsync(SaveChangesCompletedEventData eventData, Int32 result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at DataConnectors.SQLConnector.<>c__DisplayClass138_0.<<SaveDeviceMessageData>g__SaveDeviceMessage|0>d.MoveNext() in C:\Develop\Projects\Repos\JAoT.Core\DataConnectors\SQLConnector.cs:line 5469
--- End of stack trace from previous location ---
   at DataConnectors.SQLConnector.<>c__DisplayClass138_0.<<SaveDeviceMessageData>b__1>d.MoveNext() in C:\Develop\Projects\Repos\JAoT.Core\DataConnectors\SQLConnector.cs:line 5435
--- End of stack trace from previous location ---
   at DataConnectors.SQLConnector.DataContextExecuteAsync[T](Func`2 action, IServiceProvider serviceProvider) in C:\Develop\Projects\Repos\JAoT.Core\DataConnectors\SQLConnector.cs:line 114
   at DataConnectors.SQLConnector.DataContextExecuteAsync[T](Func`2 action) in C:\Develop\Projects\Repos\JAoT.Core\DataConnectors\SQLConnector.cs:line 103
   at DataConnectors.SQLConnector.SaveDeviceMessageData(IDeviceMessage deviceMessage) in C:\Develop\Projects\Repos\JAoT.Core\DataConnectors\SQLConnector.cs:line 5433

Please note that if I remove the logger (leaving the data context) the operations are fully successful: it looks like the problem is only affecting the logger, not the data context.

I also tried to get the ILoggerFactory object from the DI:

` public class DeviceMessageTrigger : IAfterSaveTrigger<Device_Message>
    {
        protected readonly JAoTSQL _context;
        protected readonly ILogger<DeviceMessageTrigger> _logger;

        public DeviceMessageTrigger(JAoTSQL context, ILoggerFactory loggerfactory)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _logger = loggerfactory?.CreateLogger<DeviceMessageTrigger>() ?? throw new ArgumentNullException(nameof(loggerfactory));
        }

        public async Task AfterSave(ITriggerContext<Device_Message> context, CancellationToken cancellationToken)
        {
            switch (context.ChangeType)
            {
                case ChangeType.Added:
                    _logger.LogError("Executing Trigger Action");
                    await _context.ServiceBroker_DeviceMessageAdded(context.Entity.DeviceMessageID, context.Entity.DeviceID);
                    break;
`

This way I do not get any error, and the trigger is called and executed as expected. But the logger does not write anything even if I made sure the instance was created successfully by the ILoggerFactory and I raised the Log level to Error to avoid the log entry to be filtered.
I checked and can confirm the async trigger is called only after  SaveAsync calls not to mix sync and async code and, in addition, please note that I moved the logging configuration before and after the configuration of the db context and trigger components, but did not change the behavior.

Did I miss anything or is it a problem with the Triggers?

Thank you

**Comment by koenbeuk** [comment]
I think the issue may be related to registering the trigger within the `OnConfiguring` method. I suspect that during runtime, it uses the internal service provider of EF core to resolve services as there is no application service provider and it fails to resolve the proper logging services.

Can you try and either remove registering the trigger within the `OnConfiguring` method and always make sure that you use DI to get a DbContext?

**Comment by Piggy69** [comment]
if I remove the registration within the OnConfiguring method, I don't get the trigger working anymore:

`
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(_connectionString, x =>
                {
                    x.UseNetTopologySuite();
                    x.CommandTimeout(GetConnectionTimeout());
                });
                //optionsBuilder.UseTriggers(t =>
                //{
                //    t.AddAssemblyTriggers(typeof(JAoTSQL).Assembly);
                //});
            }
        }
`

and I also double checked again (I am monitoring just a single operation, so I can be sure) to make sure the dbcontext for that operation is created by the DI container, it is called from here:

`        public static async Task<T> DataContextExecuteAsync<T>(Func<JAoTSQLContext, Task<T>> action, IServiceProvider serviceProvider)
        {
            using IServiceScope scope = serviceProvider.CreateScope();
            using JAoTSQL sql = scope.ServiceProvider.GetRequiredService<JAoTSQL>();
            return await action(sql);
        }`


Just to explore the issue, I tried to inject into the dbcontext my IServiceProvider: and to pass it to the trigger configuration:

` protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(_connectionString, x =>
                {
                    x.UseNetTopologySuite();
                    x.CommandTimeout(GetConnectionTimeout());
                });
                optionsBuilder.UseTriggers(t =>
                {
                    t.AddAssemblyTriggers(typeof(JAoTSQL).Assembly);
                    t.UseApplicationScopedServiceProviderAccessor(s => _serviceProvider);
                });
            }
        }`
this actually solved the problem of the log creation, but ended up creating the usual problems related to injecting a singleton service into a scoped one.

I think it is a problem about injecting the right serviceProvider into the instance, but - at the moment - I did not find a solution.

**Comment by Piggy69** [comment]
Maybe not the most elegant solution, but I am ending up using a static method to get the logger instead of requesting it from the DI container:

`   private readonly ILogger<DeviceMessageAction> _logger;
        public DeviceMessageTrigger(JAoTSQLContext context) : base(context)
        {
            _logger = Common.Extensions.DefaultLoggerFactory.CreateLogger<DeviceMessageAction>(); //static method
        }
`

it works and I get the logging capabilities.

If you have some ideas or news, I am still very interested in obtaining the result by using the full DI workflow.

**Comment by trevster344** [comment]
I am having the same issue. If I move configuration out of `OnConfigure` it simply never fires triggers. If I use the `OnConfiguring`, I cannot resolve any scoped dependencies in my triggers. I've attempted to inject the service provider into the constructor of my `DBContext` and then use `UseApplicationScopedServiceProviderAccessor` but it ends up generating another error after sometime about more than twenty `IServiceProvider` being created. Any recommendations on how I can get the scoped service provider into my DBContext?
