### ISSUE TITLE
The entity type 'Dictionary`2Proxy' was not found

### ISSUE THREAD

**Issue by dennisrahmen** [koenbeuk/EntityFrameworkCore.Triggered#182]
I am using this library to trigger notifications on updates to my entities.
For that I created a trigger where I call my `MailService` to send mails via MailJet.

In that MailService I keep track of the mails send and save that as records in a separate table, so I can check later wich mails have been send already.

This worked fine without the triggers but now that I copied the notification code into a trigger I get the following error:
```The entity type 'Dictionary`2Proxy' was not found. Ensure that the entity type has been added to the model.```

When I comment the line where the `MailService` saves the send mails to the database it works, so based on the stack trace below I would assume that this library somehow captures changes that should not be tracked.
```
info: EntityFrameworkCore.Triggered.TriggerSession[0]
      Invoking trigger: iTS_Service.Triggers.Notifications.UpdateAppointmentTrigger as EntityFrameworkCore.Triggered.IAfterSaveAsyncTrigger`1[iTS_Service.Data.Models.Appointment]
fail: Microsoft.EntityFrameworkCore.Update[10000]
      An exception occurred in the database while saving changes for context type 'iTS_Service.Data.ApplicationDbContext'.
      System.InvalidOperationException: The entity type 'Dictionary`2Proxy' was not found. Ensure that the entity type has been added to the model.
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateEntry(Object entity)
         at Microsoft.EntityFrameworkCore.DbContext.EntryWithoutDetectChanges(Object entity)
         at Microsoft.EntityFrameworkCore.DbContext.Entry(Object entity)
         at EntityFrameworkCore.Triggered.Internal.TriggerContextTracker.CaptureChanges()
         at EntityFrameworkCore.Triggered.TriggerSession.CaptureDiscoveredChanges()
         at EntityFrameworkCore.Triggered.Internal.TriggerSessionSaveChangesInterceptor.SavingChangesAsync(DbContextEventData eventData, InterceptionResult`1 result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

Also I checked, there are no dictionaries in any of my models for the database as thats not supported by EF Core. There are once in local variables but commenting those out does not fix the problem and it also should not be tracked regardless.

My code:
[My "UpdateAppointmentTrigger"](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/files/12352738/UpdateAppointmentTrigger.TXT)

**Comment by koenbeuk** [comment]
> there are no dictionaries in any of my models for the database as thats not supported by EF Core.

I don't see a direct issue with the code that you provided however the error message suggests that you're still trying to save a Dictionary property. Are you sure that the mail requests are not somehow stored in the DbContext? You could use the DebugView of the DbContext to check what entity this dictionary is linked to when you get this exception. I suspect it might not be related to this library.

**Comment by dennisrahmen** [comment]
Thanks for the quick response.
There is a dict in the `internalMailRequest` but not in the `MailRequest` which will get saved to the database.

While further checking, I found that removing `options.UseLazyLoadingProxies();` solves the issue as suggested by the ```Dictionary`2Proxy'``` proxy part.

Should this library work with lazy loading proxies?

**Comment by koenbeuk** [comment]
Yes, this library is compatible with lazy loading proxies.

**Comment by dennisrahmen** [comment]
Then the problem is how I am using the lazy loading proxies and I have to check that.
Thanks for the help, much appreciated!
