### ISSUE TITLE
Provide DbContext with ITriggerContext

### ISSUE THREAD

**Issue by furier** [koenbeuk/EntityFrameworkCore.Triggered#183]
I have not researched how and why things are done the way they are but on the top of my head I wonder why the `DbContext` could not be provided together with the `ITriggerContext`?

We use **GraphQL HotChocolate** with our API and it requires us to wire up EF Core the following way, because each field resolver needs it's own `DbContext` to be able to do work in parallell.

```cs
builder.Services
    .AddPooledDbContextFactory<MyDbContext>(
        o => o
            .UseSqlServer(builder.Configuration["DbConnectionString"]!)
            .UseTriggers(
                b => b
                    .AddAssemblyTriggers(ServiceLifetime.Scoped, typeof(GatewayDbContext).Assembly)
                    .UseApplicationScopedServiceProviderAccessor(p => p.GetRequiredService<IHttpContextAccessor>().HttpContext?.RequestServices ?? p.CreateScope().ServiceProvider)
            )
            .EnableDetailedErrors(!isProduction)
            .EnableSensitiveDataLogging(!isProduction)
    )
    .AddScoped<MyDbContextScopedFactory>()
    .AddTransient(sp => sp.GetRequiredService<MyDbContextScopedFactory>().CreateDbContext());
```

Now when I implement soft delete with a trigger like this, a different `DbContext` is injected into the trigger then the one which triggered the trigger in the first place, so the entity gets deleted anyway because the original `DbContext` doesn't know that the entry's state changed to `Modified`...

```cs
public class EntityDeletedTrigger : IBeforeSaveTrigger<ISoftDeleteEntity>
{
    private readonly MyDbContext _dbContext;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public EntityDeletedTrigger(MyDbContext dbContext, IHttpContextAccessor httpContextAccessor)
    {
        _dbContext = dbContext;
        _httpContextAccessor = httpContextAccessor;
    }

    public Task BeforeSave(ITriggerContext<ISoftDeleteEntity> context, CancellationToken cancellationToken)
    {
        if (context.ChangeType is ChangeType.Deleted)
        {
            var entry = _dbContext.Entry(context.Entity);
            context.Entity.DeletedBy = _httpContextAccessor.HttpContext?.User.GetUsername() ?? "Unknown";
            context.Entity.DeletedDate = DateTimeOffset.UtcNow;
            context.Entity.IsDeleted = true;
            entry.State = EntityState.Modified;
        }

        return Task.CompletedTask;
    }
}
```

If the `ITriggerContext` had a `DbContext` property with the `DbContext` that triggered the trigger, the entry's state would be correctly set to `Modified` and it would not be deleted. 🤷‍♂️

**Comment by furier** [comment]
I'm sorry, I somehow overlooked the `AddTriggeredPooledDbContextFactory` method 🤷‍♂️

**Comment by koenbeuk** [comment]
That is correct, `AddTriggeredPooledDbContextFactory` takes care of ensuring that the `ApplicationScopedServiceProviderAccessor` is set accordingly.

Otherwise there is `ITriggerContext<>.GetDbContext` extension method in the `EntityFrameworkCore.Triggered.Extensions` nuget package that allows you to get the dbContext from the triggerContext.
