### ISSUE TITLE
context.UnmodifiedEntity is identic to context.Entity on update

### ISSUE THREAD

**Issue by mihaiblaga1** [koenbeuk/EntityFrameworkCore.Triggered#184]
Hello!

I'm trying to create a simple trigger, that updates a message every time a property on an object is updated. My problem is that every time I check for differences between context.UnmodifiedEntity and context.Entity, all the object properties are exactly the same. I checked and it updates the required fields on the Survey entity accordingly in the database. Has anyone encountered this issue also? Any ideeas? Leaving the trigger and the configs here, I might also have missed something. 

I'm using EntityFrameworkCore.Triggered v 3.2.2
Also tried with IAfterSaveTrigger, IBeforeSaveCompleted, IBeforeSaveStarting, IAfterSaveCompleted, IAfterSaveStarted trigger types

Thanks!
![image](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/assets/127728362/c5e9b5e9-df94-46fa-b0db-559a90bc550a)
![image](https://github.com/koenbeuk/EntityFrameworkCore.Triggered/assets/127728362/3372cac2-7266-4aed-bc24-0d28f4f3148c)

**Comment by koenbeuk** [comment]
The code that you shared looks correct. 

> every time I check for differences between context.UnmodifiedEntity and context.Entity, all the object properties are exactly the same

Are the values the new values or the old values?

**Comment by mihaiblaga1** [comment]
> The code that you shared looks correct.
> 
> > every time I check for differences between context.UnmodifiedEntity and context.Entity, all the object properties are exactly the same
> 
> Are the values the new values or the old values?

The new values
