### ISSUE TITLE
SaveChangesAsync scales non-linearly even on unregistered entities

### ISSUE THREAD

**Issue by rowcla** [koenbeuk/EntityFrameworkCore.Triggered#188]
Have found that while saving changes for entities normally appears to be fairly linear in time allotment (without triggers), doing it with triggers set up, even if the updated entities don't have any registered triggers, the time duration increase is non-linear, and scales poorly.

For example, when dealing with 10k rows of a single entity, it took me 6s without triggers, and 8s with triggers. When dealing with 100k rows, it took 1 minute without triggers, and over 11 minutes with triggers.

I am currently hoping to find a way to modify the library to mitigate this (possibly at the expense of features that I'm not using).

Noting that I'm forced to use pre version 3, due to running this on an application on dotnet 5

**Comment by koenbeuk** [comment]
I've regularly benchmarked the performance impact of this library and have found that this library roughly scales linearly with EF Core raw.

I did notice that logging can cause a performance drop as by default this library is a bit aggressive in the logging department, however this should not have a  non-linear effect on scalability.

Can you share a repro?

**Comment by rowcla** [comment]
I'm unfortunately not really able to provide a repro at this stage, it's interesting though that you've observed differently. I assume you've benchmarked in v2.4.0 etc?

**Comment by jurion** [comment]
I can confirm that librarie uses a lot of CPU in “big data” scenarios, where context might have up to 10K entities (No triggers on them, and they are not even modified in anyway)
We published in production a small trigger (Trigger itself does maximum of 2-3 SQL querries). 
We noticed a spike from 5% average CPU usage to 100% and needed to add extra 2 servers. 
We immediately (After the weekend) pushed a hotfix which simply removed “useTriggers” and instantly CPU wasd down to usual 4-5 %.
