### ISSUE TITLE
How can we listen to the server trigger from a JS client app?

### ISSUE THREAD

**Issue by BenHayat** [koenbeuk/EntityFrameworkCore.Triggered#87]
Hi;
In Firebase Firestore system, Google offers a client SDK to connect to backend Firesore. Part of this SDK, is a listener method that we can subscribe to and anytime there is a change in the DB, this listener fetch the changed data and provides it to us at client side. And if we have our data bound to the view, the view shows new data.

Using your product that gets triggered on the server side, what would be the best strategy to accomplish the same on the client side, by having a listener?

Thank you for great work.

**Comment by koenbeuk** [comment]
You would need to employ something like [SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/introduction?view=aspnetcore-5.0) in order for the server to push messages to the client, assuming that you have a hub setup:

```csharp
class PublishEntityChanged : IAfterSaveTrigger<object>{
    readonly IHubContext<MyHub> _myHubContext;

    public PublishEntityChanged(IHubContext<MyHub> myHubContext) { 
        _myHubContext = myHubContext
    }

    public async Task AfterSave(ITriggerContext<object> context, CancellationToken cancellationToken){
        await _myHubContext.Clients.All.SendAsync("EntityChanged", new {
            ChangeType = context.ChangeType,
            EntityType = context.Entity.GetType().Name,
            Entity = context.Entity
        });
    }
}
```

This trigger would call a method: 'EntityChanged' on all currently connected clients with some information on what has changed

**Comment by BenHayat** [comment]
@koenbeuk 👍 

Thanks. I was thinking of the same using SignalR.
Awesome!
