### ISSUE TITLE
Transient triggers should share state between its life-cycle implementations 

### ISSUE THREAD

**Issue by koenbeuk** [koenbeuk/EntityFrameworkCore.Triggered#93]
Currently transient triggers do not share state between the different lifecycles, e.g;
```csharp
class MyTrigger : IBeforeSaveTrigger<object>, IAfterSaveTrigger<object> { 
    int _counter;
    
    public Task BeforeSave(ITriggerContext<object> context, CancellationToken _) {
        _counter += 1;
        return Task.CompletedTask;
    }
    
    public Task AfterSave(ITriggerContext<object> context, CancellationToken _) {
        Console.WriteLine($"Counter: {_counter}");
        return Task.CompletedTask;
    }
}
```
Will always print 0 when registered as a transient trigger since state is not shared between the 2 lifecycles. If we were to register  the trigger as a Scoped trigger then the counter may be  > 1 if there are multiple entities within the changeset. 

It makes sense to have transient triggers still share the same state so that a Trigger is only transient per unique Entity/Trigger, not per unique Entity/Lifecyle as its currently.

**Comment by koenbeuk** [comment]
As triggers are currently registered in DI as either transient/scoped/singleton, for this to work we would need to introduce a new and custom lifetime mode. This could come in a few forms.

Assuming we have the following triggers:
```csharp
public class StudentTrigger : IBeforeSaveTrigger<Student>, IAfterSaveTrigger<Student> {
    ...
}
```

1. Add an additional way of [registering](url) triggers, through a factory
```csharp
interface ITriggerFactory<TEntity>  {
    IEnumerable<IBeforeSaveTrigger<TEntity>> ResolveBeforeSave(ITriggerContext<TEntity> context);
    IEnumerable<IAfterSaveTrigger<TEntity>> ResolveAfterSave(ITriggerContext<TEntity> context);
}

services.AddScoped<ITriggerFactory<Student>, ManagedLifetimesTriggerFactory<StudentTrigger>>();
```

A factory would then be able to yield 0 to n triggers for each change. This has the advantage of allowing different types of TriggerFactories to coexist. One such factory could be a ConditionalTriggerFactory where you may want to prevent triggers from getting executed (and therefore logged) based on some preconditions. It would also come with some cost:

- For each change, we would have to scout DI twice for interested triggers. once by looking for the actual trigger implementation (e.g. IBeforeSave<Student>) and once for looking for factories). 
- Trigger registration gets more complex (this could be somewhat remedied with extension methods such as ```services.AddTriggerType<StudentTrigger>()```
- A user could potentially register a trigger as both a direct trigger within DI as well as through a Factory.

Thus, this would add additional complexity in our trigger discovery logic. We could consider deprecating support for directly registered triggers and move forward with factories as the primary way of registering triggers however this would be a breaking change.

2. Create special wrapping triggers
```csharp
services.AddScoped<SharedTriggerType<StudentTrigger>>();
services.AddTransient<IBeforeSaveTrigger<Student>>(sp => sp.GetService<SharedTriggerType<StudentTrigger>>())
services.AddTransient<IAfterSaveTrigger<Student>>(sp => sp.GetService<SharedTriggerType<StudentTrigger>>());
```
SharedTriggerType could then act as a factory and manage different actual trigger instances. This gives us much of what TriggerFactories would offer without the need to change anything fundamental. This could even be released as an extension package and with the some clever naming and extension methods would be as trivial to use as we use triggers today.

I'm going to prototype an implementation of method 2 first and see if it fits the needs... more to come soon

**Comment by koenbeuk** [comment]
In the latest version we're reorienting on registering triggers with the DbContext directly. These are then already wrapped up in Factories so the intend here is to use this same factory model to manage lifetimes of trigger instances based on the entity itself. In short: I'm going to try and solve this problem with the first proposal given in my last comment. Negative performance implications are already solved with earlier works on factory support.

**Comment by furier** [comment]
I believe this is the issue I am having with my trigger, `IAfterSaveTrigger<Transaction>` and `IAfterSaveCompletedTrigger` each resolve their own instance, meaning the content of `AfterSaveCompleted` never gets executed as `_execute` is not set to `true`.

```
public class TransactionAfterSaveCompletedTrigger : IAfterSaveTrigger<Transaction>, IAfterSaveCompletedTrigger
{
    private readonly ITransactionService _transactionService;
    private readonly IDictionary<Guid, (ChangeType changeType, Transaction transaction)> _transactions = new ConcurrentDictionary<Guid, (ChangeType, Transaction)>();
    private bool _execute;

    public TransactionAfterSaveCompletedTrigger(ITransactionService transactionService)
    {
        _transactionService = transactionService;
    }

    public Task AfterSave(ITriggerContext<Transaction> context, CancellationToken cancellationToken)
    {
        _execute = true;
        
        var transaction = context.Entity;

        if (transaction.PersonId.HasValue && transaction.Start.HasValue)            
            _transactions.TryAdd(transaction.Id, (context.ChangeType, transaction));

        return Task.CompletedTask;
    }

    public async Task AfterSaveCompleted(CancellationToken cancellationToken)
    {
        if (!_execute) return;
        
        var transactions = _transactions.Values
            .Select(x => (x.changeType, x.transaction.Id, x.transaction.TransactionStatus, x.transaction.SourceTransactionId, x.transaction.PersonId!.Value, x.transaction.Start!.Value))
            .ToList();

        await _transactionService.CalculateTransactionsAsync(transactions, cancellationToken);
    }
}
```

**Comment by koenbeuk** [comment]
@DavidErben 

Great to hear that you're successful with this library! I'm curious as to why the ServiceLifetime overload did not work for you. when you have a chance, can you open up a new issue for that?

I haven't looked back at this issue yet due to different priorities and I'm also not entirely sure what this feature should look like yet.

In v2.3 we now have an interface that we can implement: `ITriggerInstanceFactory<Foo>` which is responsible for creating Trigger class instances (e.g. FooTrigger). This could be used to customized to return trigger instances that are associated with the changed entity. This way each Entity could share the same trigger instance in different lifecycles (e.g. in your case in the Before and After lifecycle you could store your flag on the trigger instance as this instance will only be shared by 1 entity).

An alternative an perhaps better design is to add a Bag property on the TriggerContext, This would allow different triggers to add attach additional data to a TriggerContext, what that would mean in your use case:

```csharp
class BeforeSaveFoo : IBeforeSaveTrigger<Foo>, IAfterSaveTrigger<Foo> {
     public async Task BeforeSave(TriggerContext context, CancellationToken cancellationToken) {
           if (....) {
               context.Bag["MyFlag"] = true;
           }
     }

     public async Task AfterSave(TriggerContext context, CancellationToken cancellationToken) {
           if (context.Bag["MyFlag"] == true) {
               SomethingHeroic();
           }
     }
}
```

I slightly lean towards the latter (Bag) approach as it opens up different scenario's including the sharing of additional state between Triggers. I'm curious to hear your suggestions.

Thanks!

**Comment by koenbeuk** [comment]
Regarding the Bag proposal, this will also bring into question the current workings of Triggers. For one, should the bag be associated with the TriggerContext instance or the Entity?

To exemplify: In the case of a SoftDelete, where my BeforeSave trigger would change the state of an entity from Deleted to Modified, this will in turn create a new TriggerContext during the next invocation cycle which reflects the new EntityState. Should this carry the same Bag as was associated with the TriggerContext that represented the Deleted state of that Entity?

With that, currently Triggers are guaranteed to execute, even if they are no longer relevant. With that I mean: Changing the Entity state from Deleted to Modified in a SoftDelete example will still continue to raise additional BeforeSave triggers with the Deleted TriggerContext instance (assuming that there are additional Triggers registered). Perhaps TriggerContext deserves an additional method: `context.StopPropagation()` which basically ensures that for that TriggerContext, no additional triggers will be executed. 

Lots of questions and considerations that I'm currently considering. Input would be welcome here

**Comment by DavidErben** [comment]
Hi Koen,

thanks for your quick reply! Definitely no easy decision on how to implement it, especially since we are probably not aware of all possible scenarios other users have in mind. But in general I think the bag idea is good, since it is a generic way to store a state or any relevant data which could be useful for evaluation at a later stage. Maybe you can find a way to let the user specfiy if the bag shall be associated with either the context instance or the entity. Or the context stores both, global and entity related bags?

In my specific case I am using the IAfterSaveCompletedTrigger which is non-generic and has no context. I am using it because I want to send out the SignalR notification just once after all work has been done. Of course this could also be achieved with a second flag (notificationSent), so then it would be possible to do it just in the AfterSave method as well. My current implementation looks like this:

	public class SendNotificationTrigger : IAfterSaveTrigger<Order>, IAfterSaveCompletedTrigger
	{
		private readonly INotificationService _notificationService;
		private bool _sendNotification = false;

		public SendNotificationTrigger(INotificationService notificationService)
		{
			_notificationService = notificationService;
		}

		public Task AfterSave(ITriggerContext<Order> context, CancellationToken cancellationToken)
		{
			if (context.Entity.PatientDataProvider == false)
			{
				_sendNotification = true;
			}

			return Task.CompletedTask;
		}

		public async Task AfterSaveCompleted(CancellationToken cancellationToken)
		{
			if (_sendNotification)
			{
				await _notificationService.BroadcastUpdateDashboardAsync();
			}

			await Task.CompletedTask;
		}
	}

The solution with the second flag would look like this, maybe it is actually easier after all.

	public async Task AfterSave(ITriggerContext<Order> context, CancellationToken cancellationToken)
	{
		if (context.Entity.PatientDataProvider == false && _notificationSent == false)
		{
			await _notificationService.BroadcastUpdateDashboardAsync();
			_notificationSent = true;
		}
	}

My goal is basically to detect if any "Order" which is a "PatientDataProvider" has been modified/added/deleted during this save operation. If so, I send the dashboard update message, so that the UI updates and reflects the latest changes.

**Comment by koenbeuk** [comment]
@DavidErben 

When you manually register triggers with your application DI container then you need to make sure that each registration shares the same instance. This can be done with the following:

```csharp
services.AddScoped<FooTrigger>();
services.AddTransient<IAfterSaveTrigger<Foo>>(sp => sp.GetRequiredService<FooTrigger>());
services.AddTransient<IAfterSaveCompletedTrigger>(sp => sp.GetRequiredService<FooTrigger>());
```
Otherwise when using AddTrigger on the TriggersContextOptionsBuilder, this will already ensure that by default: the lifetime of a trigger instance is Scoped and each lifecycle interface reuses that same scoped instance.

**Comment by koenbeuk** [comment]
I have a hypothetical fix for this issue implemented in #115 

This exposes a new EntityBag property on the TriggerContext which in turn can be used to associate additional items with the entity for the duration of the Trigger session.

A sample usage is given here: https://github.com/koenbeuk/EntityFrameworkCore.Triggered/blob/trigger-entity-state-management/test/EntityFrameworkCore.Triggered.IntegrationTests/EntityBags/EntityBagsTestScenario.cs

Feedback is welcome

**Comment by DavidErben** [comment]
> 
> 
> @DavidErben
> 
> When you manually register triggers with your application DI container then you need to make sure that each registration shares the same instance. This can be done with the following:
> 
> ```cs
> services.AddScoped<FooTrigger>();
> services.AddTransient<IAfterSaveTrigger<Foo>>(sp => sp.GetRequiredService<FooTrigger>());
> services.AddTransient<IAfterSaveCompletedTrigger>(sp => sp.GetRequiredService<FooTrigger>());
> ```
> 
> Otherwise when using AddTrigger on the TriggersContextOptionsBuilder, this will already ensure that by default: the lifetime of a trigger instance is Scoped and each lifecycle interface reuses that same scoped instance.

Yes, this was the way I did it when using the AfterSaveCompleted trigger. Now I changed it and I am using only the AfterSave trigger, but I have to specify the lifetime explicitely, otherwise it does not keep its state. This is the trigger now:

    public class SendNotificationTrigger : IAfterSaveTrigger<Order>
    {
        private readonly INotificationService _notificationService;
        private bool _notificationSent = false;

        public SendNotificationTrigger(INotificationService notificationService)
        {
            _notificationService = notificationService;
        }

        public async Task AfterSave(ITriggerContext<Order> context, CancellationToken cancellationToken)
        {
            if (context.Entity.PatientDataProvider == false && _notificationSent == false)
            {
                await _notificationService.BroadcastUpdateDashboardAsync();
                _notificationSent = true;
            }
        }
    }

And this is the registration of it:

    triggerOptions.AddTrigger<SendNotificationTrigger>(ServiceLifetime.Scoped);

But if I register it without explicitely setting the ServiceLifetime.Scoped is does not work. So default behavior is probably transient lifetime? For me that is fine, works well like this if I define the scope manually.

Will check out the new bag implementation in the next days, thank you!

**Comment by koenbeuk** [comment]
@DavidErben Yes my bad, the default Lifetime for AddTrigger is Transient, not Scoped. I've updated my reply above. Thanks for pointing that out!
